### ISSUE TITLE
I can't console log (the responses are undefined)!

### ISSUE THREAD

**Issue by ellennewellevans** [Juwami/Weather-Wear#33]
tried creating a variable to hold the value of the gender and temp inputs, but logging them shows undefined

**Comment by SeanTumulakNguyen** [comment]
added code to return the value of genderChosen after giving the string value to the variable. Also added code into the submit function so it can happen simultaneously.
![image](https://user-images.githubusercontent.com/40397599/59231781-efc95e80-8baf-11e9-9b63-492c846b8003.png)

**Comment by ellennewellevans** [comment]
Whoooooooo!!!!!

**Comment by SeanTumulakNguyen** [comment]
Oh the other one was finished Lol
